# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=30)),
                ('game_state', models.TextField()),
            ],
        ),
    ]
