# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='game_columns',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='board',
            name='game_num_of_bombs',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='board',
            name='game_rows',
            field=models.IntegerField(default=9),
        ),
    ]
