# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_auto_20190310_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='game_state',
            field=models.TextField(default=''),
        ),
    ]
