# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0005_auto_20190310_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='game_id',
            field=models.IntegerField(),
        ),
    ]
