# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0006_auto_20190310_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='game_id',
            new_name='game_code',
        ),
    ]
