# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0010_board_game_guistring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
